import { useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import { Activity, Cable, ChevronRight, CirclePlus, Computer, KeyRound, LayoutDashboard, ShieldCheck, Users } from "lucide-react";
import "./styles.css";

const API = import.meta.env.VITE_API_URL ?? "http://localhost:8080/api/v1";
type Device = { id: string; name: string; status: string; latency_ms: number; last_seen: string };
type Tunnel = { spec: { id: string; name: string; kind: "tcp" | "http"; public_port: number; local_host: string; local_port: number; enabled: boolean }; device_id: string; status: string; connections: number };
type Summary = { devices: number; online_devices: number; tunnels: number; active_connections: number };
const request = <T,>(path: string, options?: RequestInit) => fetch(`${API}${path}`, options).then(async response => { if (!response.ok) throw new Error(await response.text()); return response.json() as Promise<T>; });

function App() {
  const [tab, setTab] = useState("概览"); const [summary, setSummary] = useState<Summary>(); const [devices, setDevices] = useState<Device[]>([]); const [tunnels, setTunnels] = useState<Tunnel[]>([]); const [error, setError] = useState(""); const [showForm, setShowForm] = useState(false);
  const refresh = async () => { try { const [s, d, t] = await Promise.all([request<Summary>("/summary"), request<Device[]>("/devices"), request<Tunnel[]>("/tunnels")]); setSummary(s); setDevices(d); setTunnels(t); setError(""); } catch (e) { setError(e instanceof Error ? e.message : "无法连接到管理服务"); } };
  useEffect(() => { refresh(); const timer = setInterval(refresh, 7000); return () => clearInterval(timer); }, []);
  const addTunnel = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); try { await request<Tunnel>("/tunnels", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: form.get("name"), kind: form.get("kind"), public_port: Number(form.get("port")), local_host: form.get("host"), local_port: Number(form.get("localPort")), device_id: form.get("device"), max_connections: 100 }) }); setShowForm(false); refresh(); } catch (e) { setError(e instanceof Error ? e.message : "无法创建隧道"); } };
  const toggle = async (id: string) => { await request(`/tunnels/${id}/toggle`, { method: "POST" }); refresh(); };
  return <div className="app-shell"><aside><div className="brand"><span className="brand-mark"><Cable size={19}/></span><span>Tunnel<br/><b>Control</b></span></div><nav>{[["概览", LayoutDashboard], ["隧道", Activity], ["设备", Computer], ["成员", Users], ["访问令牌", KeyRound]].map(([label, Icon]) => <button key={label as string} className={tab === label ? "active" : ""} onClick={() => setTab(label as string)}><Icon size={17}/>{label as string}</button>)}</nav><div className="secure"><ShieldCheck size={16}/><span>管理平面<br/><b>仅限管理员</b></span></div></aside><main><header><div><p className="eyebrow">工作区 / 默认</p><h1>{tab}</h1></div><div className="header-status"><span className="dot"/>服务运行中 <button className="icon-button" aria-label="刷新数据" onClick={refresh}><Activity size={17}/></button></div></header>{error && <div className="notice"><b>连接提示</b>{error}</div>}{tab === "概览" && <Overview summary={summary} devices={devices} tunnels={tunnels} onCreate={() => setShowForm(true)} />}{tab === "隧道" && <TunnelList tunnels={tunnels} devices={devices} onCreate={() => setShowForm(true)} onToggle={toggle}/>} {tab === "设备" && <DeviceList devices={devices}/>} {!["概览", "隧道", "设备"].includes(tab) && <Empty title={`${tab}管理即将接入`} description="首版控制面已保留权限边界；下一步将连接 PostgreSQL 持久化与管理员会话。"/>}</main>{showForm && <TunnelForm devices={devices} onClose={() => setShowForm(false)} onSubmit={addTunnel}/>}</div>;
}
function Overview({summary, devices, tunnels, onCreate}: {summary?: Summary; devices: Device[]; tunnels: Tunnel[]; onCreate: () => void}) { return <><section className="metrics">{[["在线设备", `${summary?.online_devices ?? 0} / ${summary?.devices ?? 0}`, Computer], ["启用隧道", `${tunnels.filter(t => t.spec.enabled).length}`, Cable], ["活动连接", `${summary?.active_connections ?? 0}`, Activity]].map(([label, value, Icon]) => <div className="metric" key={label as string}><div><p>{label as string}</p><strong>{value as string}</strong></div><Icon size={21}/></div>)}</section><section className="panel"><div className="panel-heading"><div><h2>隧道状态</h2><p>由管理员分配的公网端口</p></div><button className="primary" onClick={onCreate}><CirclePlus size={17}/>新建隧道</button></div>{tunnels.length ? <TunnelRows tunnels={tunnels} devices={devices}/> : <Empty title="还没有公网入口" description="选择在线 Windows 设备，为内网服务分配一个端口。" action="新建隧道" onAction={onCreate}/>}</section></> }
function TunnelList({tunnels, devices, onCreate, onToggle}: {tunnels: Tunnel[]; devices: Device[]; onCreate:()=>void; onToggle:(id:string)=>void}) { return <section className="panel"><div className="panel-heading"><div><h2>隧道</h2><p>公网端口由管理员独占管理</p></div><button className="primary" onClick={onCreate}><CirclePlus size={17}/>新建隧道</button></div>{tunnels.length ? <><TunnelRows tunnels={tunnels} devices={devices}/><div className="table-actions">{tunnels.map(t => <button key={t.spec.id} className="quiet" onClick={() => onToggle(t.spec.id)}>{t.spec.enabled ? "停用" : "启用"} {t.spec.name}</button>)}</div></> : <Empty title="暂无隧道" description="先让客户端接入，再创建端口映射。" action="新建隧道" onAction={onCreate}/>}</section> }
function TunnelRows({tunnels, devices}:{tunnels:Tunnel[];devices:Device[]}) { return <div className="table"><div className="row label"><span>名称</span><span>公网入口</span><span>本地目标</span><span>设备</span><span>状态</span></div>{tunnels.map(t => <div className="row" key={t.spec.id}><b>{t.spec.name}<small>{t.spec.kind.toUpperCase()}</small></b><code>:{t.spec.public_port}</code><code>{t.spec.local_host}:{t.spec.local_port}</code><span>{devices.find(d => d.id === t.device_id)?.name ?? "未连接设备"}</span><span className={`status ${t.spec.enabled ? "waiting" : "off"}`}>{t.status}</span></div>)}</div> }
function DeviceList({devices}:{devices:Device[]}) { return <section className="panel"><div className="panel-heading"><div><h2>Windows 设备</h2><p>通过访问令牌注册的客户端</p></div></div>{devices.length ? <div className="devices">{devices.map(d => <article key={d.id}><span className={`device-state ${d.status}`}/><div><b>{d.name}</b><p>{d.id.slice(0, 8)} · {d.latency_ms} ms</p></div><ChevronRight size={17}/></article>)}</div> : <Empty title="等待客户端注册" description="在 Windows 客户端的“设置”中填写服务端地址和访问令牌。"/>}</section> }
function Empty({title, description, action, onAction}:{title:string;description:string;action?:string;onAction?:()=>void}) { return <div className="empty"><div className="empty-icon"><Cable size={22}/></div><h3>{title}</h3><p>{description}</p>{action && <button className="primary" onClick={onAction}><CirclePlus size={16}/>{action}</button>}</div> }
function TunnelForm({devices, onClose, onSubmit}:{devices:Device[];onClose:()=>void;onSubmit:(e:React.FormEvent<HTMLFormElement>)=>void}) { return <div className="modal-backdrop"><form className="modal" onSubmit={onSubmit}><div className="modal-head"><div><p className="eyebrow">管理员操作</p><h2>新建隧道</h2></div><button type="button" className="quiet" onClick={onClose}>关闭</button></div><label>名称<input required name="name" placeholder="例如：研发远程桌面"/></label><div className="two"><label>类型<select name="kind"><option value="tcp">TCP</option><option value="http">HTTP</option></select></label><label>公网端口<input name="port" required type="number" min="10000" max="60000" placeholder="10001"/></label></div><label>目标设备<select required name="device"><option value="">选择在线设备</option>{devices.filter(d=>d.status === "online").map(d => <option key={d.id} value={d.id}>{d.name}</option>)}</select></label><div className="two"><label>本地地址<input name="host" required defaultValue="127.0.0.1"/></label><label>本地端口<input name="localPort" required type="number" min="1" max="65535" placeholder="3389"/></label></div><div className="modal-actions"><button type="button" className="quiet" onClick={onClose}>取消</button><button className="primary" type="submit">创建隧道</button></div></form></div> }
createRoot(document.getElementById("root")!).render(<App/>);
