import { useState } from "react";
import { Activity, Cable, ChevronRight, CircleCheck, Gauge, Network, Settings, TerminalSquare } from "lucide-react";
import { createRoot } from "react-dom/client";
import "./styles.css";

const tunnels = [{name:"研发远程桌面", kind:"TCP", public:":10001", local:"127.0.0.1:3389", status:"等待服务端配置"},{name:"本地开发站点",kind:"HTTP",public:":10080",local:"127.0.0.1:5173",status:"等待服务端配置"}];
function App(){const [page,setPage]=useState("概览");const [connected,setConnected]=useState(false);const [saved,setSaved]=useState(false);return <div className="client"><aside><div className="brand"><span><Cable size={19}/></span><b>Tunnel Agent</b></div><nav>{[["概览",Gauge],["隧道",Network],["连接",Activity],["设置",Settings]].map(([name,Icon])=><button key={name as string} onClick={()=>setPage(name as string)} className={page===name?"current":""}><Icon size={17}/>{name as string}</button>)}</nav><div className="agent-state"><i className={connected?"online":""}/><div><small>后台服务</small><b>{connected?"已连接":"未连接"}</b></div></div></aside><main><header><div><p>此 Windows 设备</p><h1>DESKTOP-LOCAL</h1></div><span className={connected?"badge ok":"badge"}>{connected?"代理在线":"需要配置"}</span></header>{page==="概览"&&<Overview connected={connected} goSettings={()=>setPage("设置")}/>} {page==="隧道"&&<Tunnels connected={connected}/>} {page==="连接"&&<Connections connected={connected}/>} {page==="设置"&&<SettingsPage onSave={()=>{setSaved(true);setConnected(true)}} saved={saved}/>}</main></div>}
function Overview({connected,goSettings}:{connected:boolean;goSettings:()=>void}){return <><section className="connection"><div className="signal"><span/><span/><span/></div><div><p className="eyebrow">控制信道</p><h2>{connected?"正在与服务端同步":"连接尚未配置"}</h2><p>{connected?"后台 Windows 服务正在保持控制连接，并会在重启后自动恢复。":"填写服务器地址与访问令牌后，管理员才能将隧道下发到此设备。"}</p></div><button onClick={goSettings}>{connected?"查看设置":"开始配置"}<ChevronRight size={16}/></button></section><section className="grid"><article><p>已分配隧道</p><strong>{connected?"2":"0"}</strong><small>由管理员维护</small></article><article><p>本机延迟</p><strong>{connected?"12 ms":"--"}</strong><small>最近一次心跳</small></article><article><p>本次会话流量</p><strong>{connected?"48.2 MB":"0 B"}</strong><small>上传与下载</small></article></section><section className="panel"><div className="panel-title"><div><h2>操作日志</h2><p>本机代理的最新事件</p></div><TerminalSquare size={18}/></div><div className="logs">{connected?<><p><time>10:42:08</time><span>已完成心跳检查，延迟 12 ms</span></p><p><time>10:42:03</time><span>已同步 2 条管理员隧道策略</span></p></>:<p><time>--:--:--</time><span>等待服务端连接配置</span></p>}</div></section></>}
function Tunnels({connected}:{connected:boolean}){return <section className="panel"><div className="panel-title"><div><h2>管理员隧道</h2><p>此处仅展示状态；公网端口由管理面板分配</p></div><span className="readonly">只读</span></div>{connected?<div className="tunnels">{tunnels.map(t=><article key={t.name}><span className="tunnel-icon"><Network size={18}/></span><div><b>{t.name}</b><p><code>{t.public}</code> → <code>{t.local}</code></p></div><small>{t.kind}</small><span className="ready"><CircleCheck size={15}/>已就绪</span></article>)}</div>:<Empty text="设备尚未连接，因此没有可同步的隧道。"/>}</section>}
function Connections({connected}:{connected:boolean}){return <section className="panel"><div className="panel-title"><div><h2>实时连接</h2><p>通过此设备的公网访问</p></div><span className="readonly">最近 24 小时</span></div><Empty text={connected?"目前没有活动连接。新的访问会出现在这里。":"连接服务端后，这里会显示端口访问和流量。"}/></section>}
function SettingsPage({onSave,saved}:{onSave:()=>void;saved:boolean}){return <section className="settings"><div><p className="eyebrow">服务端注册</p><h2>连接设置</h2><p>令牌存储在 Windows 凭据管理器中，不会写入普通配置文件。</p></div><form onSubmit={e=>{e.preventDefault();onSave()}}><label>服务端地址<input required defaultValue="wss://tunnel.example.com/control" placeholder="wss://server:8443/control"/></label><label>访问令牌<input required type="password" placeholder="粘贴管理员创建的令牌"/></label><div className="service"><span><CircleCheck size={18}/></span><div><b>后台 Windows 服务</b><p>启用后将在登录与网络恢复时自动尝试重连。</p></div><input type="checkbox" defaultChecked aria-label="启用后台服务"/></div><button className="save">{saved?"已保存并连接":"保存并连接"}<ChevronRight size={16}/></button></form></section>}
function Empty({text}:{text:string}){return <div className="empty"><Activity size={21}/><p>{text}</p></div>};createRoot(document.getElementById("root")!).render(<App/>);
